add directed graph and support modules
sun-asterisk-research/table_reconstruction pull request #23
Opened 2021-09-19 15:47 UTC by manhbq-2536

## Description

Add directed graph and supported modules

Fixes #{issue number}

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Add more tests
- [ ] Others

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Create and activate the virtual environment
- Install package by running python setup.py install in the root folder
- Take the output of line segmentation and return XY coordinate of cells

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have successfully run the modified code in my local environment with no errors
- [ ] I ran the proper linters and fixed the issues pointed out to make sense
- [ ] I updated the unit test based on my edit

2021-09-20 02:33 UTC, chienlm-2537 commented on table_reconstruction/utils/cell_utils.py
> +from table_reconstruction.utils.lines_utils import is_line
anh nghĩ nên để import thế này
```suggestion
from .lines_utils import is_line
```

2021-09-20 02:40 UTC, chienlm-2537 commented on table_reconstruction/utils/lines_utils.py
> +from table_reconstruction.utils import mask_utils
```suggestion
from .mask_utils import get_hor_lines_mask, get_ver_lines_mask
```

2021-09-20 02:41 UTC, chienlm-2537 commented on table_reconstruction/utils/lines_utils.py
> +    horizontal_lines_mask = mask_utils.get_hor_lines_mask(mask, kernel_len)
```suggestion
horizontal_lines_mask = get_hor_lines_mask(mask, kernel_len)
```

2021-09-20 02:41 UTC, chienlm-2537 commented on table_reconstruction/utils/lines_utils.py
> +    vertical_lines_mask = mask_utils.get_ver_lines_mask(mask, kernel_len)
```suggestion
vertical_lines_mask = get_ver_lines_mask(mask, kernel_len)
```

2021-09-20 09:08 UTC, manhbq-2536 commented on table_reconstruction/utils/cell_utils.py
> +from table_reconstruction.utils.lines_utils import is_line
Em thấy hợp lý hơn đấy :v

2021-09-20 09:08 UTC, manhbq-2536 commented on table_reconstruction/utils/lines_utils.py
> +from table_reconstruction.utils import mask_utils
Em thấy hợp lý đó. Em sửa hết r nha :v

2021-09-20 10:36 UTC, trungtd-2436 requested changes
Chưa update requirements

2021-09-20 10:36 UTC, trungtd-2436 commented on table_reconstruction/utils/lines_utils.py
> +    tab_x1 = min(min(hor_lines[:, 0]), min(ver_lines[:, 0]))
Chưa kiểm tra điều kiện danh sách các đường rỗng

2021-09-20 10:36 UTC, trungtd-2436 commented on table_reconstruction/utils/cell_utils.py
> +    thresh: float,
Chưa có có phần đề cập đến giá trị `thresh` nên để là bao nhiêu
```suggestion
    thresh: float=15,
```

2021-09-20 10:36 UTC, trungtd-2436 commented on table_reconstruction/utils/lines_utils.py
> +def minAreaRect(coords: np.ndarray) -> List:
Đổi lại tên hàm
```suggestion
def min_area_rect(coords: np.ndarray) -> List:
```

2021-09-20 10:37 UTC, trungtd-2436 requested changes
Chưa update requirements nhé 

```
scikit-image==0.18.3
Shapely==1.7.1
```

2021-09-20 15:54 UTC, buiquangmanhhp1999 commented on table_reconstruction/utils/lines_utils.py
> +    tab_x1 = min(min(hor_lines[:, 0]), min(ver_lines[:, 0]))
Check exception này ở đây là hàm tổng ngoài cùng khi ông run cùng lúc cả line segmentation xong cho vào nhé chứ ko phải exception trong hàm

2021-09-21 01:40 UTC, chienlm-2537 approved these changes

2021-09-21 04:01 UTC, trungtd-2436 approved these changes

2021-09-21 04:01 UTC, merged