Add feature line segmentation
sun-asterisk-research/table_reconstruction pull request #7
Opened 2021-09-10 15:28 UTC by hungdd-2620

## Description

Add line segmentation feature and create a notebook for testing purpose

Fixes #{issue number}

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Add more tests
- [ ] Others

## How Has This Been Tested?

### Check new feature working as expected

- Create and activate the virtual environment and install necessary packages `pip install -r requirements.txt`

- Run `python setup.py install` in the root folder

- Run jupyter notebook by command `jupyter notebook` then open and run **example.ipynb** 
Checking the output mask and comparing the size of the input table image with predicted mask, the results show that line segmentation feature works pretty well.

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have successfully run the modified code in my local environment with no errors
- [ ] I ran the proper linters and fixed the issues pointed out to make sense
- [ ] I updated the unit test based on my edit

2021-09-15 05:17 UTC, trungtd-2436 approved these changes

2021-09-15 06:25 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +class LineDetector:
em nghĩ là để tên như thế này sẽ đúng chức năng hơn
```suggestion
class LineSegmentation:
```

2021-09-15 07:05 UTC, hungdd-2620 commented on table_reconstruction/line_segmentation/line_segment.py
> +class LineDetector:
ok a đã sửa lại rồi nhé

2021-09-15 07:56 UTC, trungtd-2436 requested changes

2021-09-15 07:56 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +        img_path: str,
Chỗ này anh để là ảnh dưới dạng numpy hoặc PIL Image luôn nhé, tại vì phần line segment sẽ nhận đầu vào là output của phần table detection

2021-09-15 07:56 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +                    print("Could not download weight, please try again!")
anh đổi print thành `logging.info` nhé

2021-09-15 08:11 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +            self.model = load_model_unet(model_path, device)
Cần thêm phần kiểm tra file weight có tồn tại không ạ

2021-09-15 10:19 UTC, hungdd-2620 commented on table_reconstruction/line_segmentation/line_segment.py
> +        img_path: str,
a đã sửa lại thành dạng numpy.array nhé

2021-09-15 10:19 UTC, hungdd-2620 commented on table_reconstruction/line_segmentation/line_segment.py
> +                    print("Could not download weight, please try again!")
a đã sửa lại rồi nhé 👍

2021-09-15 10:19 UTC, hungdd-2620 commented on table_reconstruction/line_segmentation/line_segment.py
> +            self.model = load_model_unet(model_path, device)
a đã thêm phần check file

2021-09-15 10:22 UTC, hungdd-2620 commented
Đã fix lỗi load trên các device khác nhau mà @chienlm-2537 đã report

2021-09-15 10:24 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +                    print("Could not download weight, please try again!")
vâng ạ

2021-09-15 10:25 UTC, trungtd-2436 commented on table_reconstruction/line_segmentation/line_segment.py
> +        img_path: str,
ok anh

2021-09-15 14:30 UTC, trungtd-2436 approved these changes

2021-09-16 07:32 UTC, chienlm-2537 approved these changes

2021-09-16 07:50 UTC, merged